language: node_js

notifications:
  email:
    on_success: never
    on_failure: change

install:
  - npm install
  - npm install libxmljs || true

node_js:
  - "4"
  - "6"
  - "8"
  - "node"

after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
